### ISSUE TITLE
Unable to install this operator on openshift 4.9.10 and 4.9.11

### ISSUE THREAD

**Issue by roshansthomas** [rhm-samples/behavior-analytics-services#16]
Is this operator supported on openshift 4.9 ? 
Cant find the operator in the operator hub, under Certified operators.

Have been using this yaml

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: behavior-analytics-services-operator-certified
  namespace: ibm-bas
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: behavior-analytics-services-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace

**Comment by Varsha-Shrivastava** [comment]
Hi @roshansthomas, Sorry for responding late. 
BAS doesn't support OCP 4.9.
Reason being, OCP 4.9 requires removal of deprecated k8s apis and we never released a version with the requires changes.
Also, I believe MAS also will not work with OCP4.9. Please check with MAS team once.

Regards.

**Comment by rhm-samples** [comment]
closing this ticket as no action item is needed as of now. BAS doesn't support OCP4.9 and above.
